import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Alert from "@/components/Toastify/Toastify";
import { GoogleOAuthProvider } from "@react-oauth/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Relux - Espacios y oficinas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider
      clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID as string}
    >
      <html lang="es">
        <body className={inter.className}>
          {children}
          <Alert />
        </body>
      </html>
    </GoogleOAuthProvider>
  );
}
